### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by ridaarif98** [ridaarif98/space_travlers_hub#73]
- [Project](https://github.com/ridaarif98/space_travlers_hub/projects/1)
- In this project we are two team members:
  - @medaminedev66 
  - @ridaarif98

**Comment by wandji20** [comment]
Hello, @ridaarif98 and @medaminedev66  :raised_hands: 

##### You have done exceptionally well, and have met all requirements for this project :+1:

# Status: Approved 👍 :partying_face: 

Your project has been approved, however, Keep up the good work.

## Congratulations :+1:  :fireworks: 
Good luck with your next project :mechanical_arm:  :slightly_smiling_face:_ 

 If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
